package com.googlecode.cqengine.query.option;

public enum ConcurrentRadixTreeLongestPrefixMatch {

    CONCURRENT_RADIX_TREE_LONGEST_PREFIX_MATCH_BY_ATTRIBUTE,

    CONCURRENT_RADIX_TREE_LONGEST_PREFIX_MATCH_BY_LOOKUP,

    CONCURRENT_RADIX_TREE_LONGEST_PREFIX_MATCH_BY_VALUE;
}
